/**
 * SystemDesignReportExporter — Generates Dossier Reports for Interviews & Evaluations
 * 
 * Exports Markdown and JSON assessment records containing candidate grades,
 * napkin-math capacity sizing, detected SPOF vulnerabilities, and recommendations.
 */

import {
  SystemDesignScenario,
  ArchitectureEvaluationResult,
} from '../../engine/scenarios/ScenarioTypes';
import { CapacityParameters } from '../../engine/scenarios/CapacityEstimator';
import { showSuccessAlert } from '../../utils/alerts';

export class SystemDesignReportExporter {
  public static generateMarkdown(
    scenario: SystemDesignScenario,
    evaluation: ArchitectureEvaluationResult,
    capacityParams: CapacityParameters,
    hintsPenalty: number = 0
  ): string {
    const lines: string[] = [];

    lines.push(`# System Design Interview Evaluation Dossier`);
    lines.push(`**Scenario:** ${scenario.title} (${scenario.difficulty.toUpperCase()} Tier)`);
    lines.push(`**Target SLA:** ${scenario.targetSlaPercentage}% Availability | P99 < ${scenario.requirements.targetP99Ms}ms`);
    lines.push(`**Evaluation Date:** ${new Date().toISOString()}`);
    lines.push(`\n---\n`);

    lines.push(`## 1. Executive Scorecard`);
    lines.push(`- **Letter Grade:** **${evaluation.grade}**`);
    lines.push(`- **Composite Score:** ${evaluation.overallScore} / 100`);
    lines.push(`- **Hint Penalty Deducted:** -${hintsPenalty} pts`);
    lines.push(`- **Estimated Monthly Cloud Cost:** $${evaluation.estimatedMonthlyCostUsd.toLocaleString()} USD`);
    lines.push(`\n> **Interviewer Verdict:** ${evaluation.interviewerVerdict}\n`);

    lines.push(`## 2. Pillar Evaluation Breakdown`);
    lines.push(`| Pillar | Score | Verdict | Feedback |`);
    lines.push(`|---|---|---|---|`);
    evaluation.metrics.forEach((m) => {
      lines.push(`| ${m.name} | ${m.score}% | ${m.verdict.toUpperCase()} | ${m.feedback} |`);
    });

    lines.push(`\n## 3. Back-of-the-Envelope Capacity Estimations`);
    lines.push(`- **Daily Active Users (DAU):** ${capacityParams.dailyActiveUsers.toLocaleString()}`);
    lines.push(`- **Read/Write Ratio:** ${capacityParams.readsPerUserPerDay}:${capacityParams.writesPerUserPerDay}`);
    lines.push(`- **Average Write Size:** ${capacityParams.avgWriteSizeBytes} bytes`);
    lines.push(`- **Peak Multiplier:** ${capacityParams.peakMultiplier}x`);
    lines.push(`- **Data Retention Horizon:** ${capacityParams.retentionYears} years`);

    lines.push(`\n## 4. Single Points of Failure (SPOFs) & Vulnerabilities`);
    if (evaluation.spofsDetected.length === 0) {
      lines.push(`✅ **Zero critical SPOFs identified.** Architecture demonstrates robust high availability and automated failover.`);
    } else {
      evaluation.spofsDetected.forEach((spof, idx) => {
        lines.push(`### ${idx + 1}. [${spof.riskLevel.toUpperCase()}] ${spof.subsystem}`);
        lines.push(`- **Description:** ${spof.description}`);
        lines.push(`- **Remediation:** ${spof.remediation}`);
      });
    }

    lines.push(`\n## 5. Architectural Strengths & Bottlenecks`);
    lines.push(`### Strengths:`);
    evaluation.strengths.forEach((s) => lines.push(`- ${s}`));
    if (evaluation.bottlenecks.length > 0) {
      lines.push(`\n### Bottlenecks Identified:`);
      evaluation.bottlenecks.forEach((b) => lines.push(`- ${b}`));
    }

    lines.push(`\n---\n*Generated by Distributed Systems Simulator v0.1.0 — FAANG System Design Interview Sandbox*`);
    return lines.join('\n');
  }

  public static async copyToClipboard(
    scenario: SystemDesignScenario,
    evaluation: ArchitectureEvaluationResult,
    capacityParams: CapacityParameters,
    hintsPenalty: number = 0
  ): Promise<void> {
    const md = this.generateMarkdown(scenario, evaluation, capacityParams, hintsPenalty);
    if (navigator.clipboard) {
      await navigator.clipboard.writeText(md);
    }
    await showSuccessAlert(
      'Report Copied!',
      'System design evaluation report copied to clipboard in Markdown format.'
    );
  }

  public static downloadMarkdown(
    scenario: SystemDesignScenario,
    evaluation: ArchitectureEvaluationResult,
    capacityParams: CapacityParameters,
    hintsPenalty: number = 0
  ): void {
    const md = this.generateMarkdown(scenario, evaluation, capacityParams, hintsPenalty);
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `system-design-scorecard-${scenario.id}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
}
